theme = "dracula"

[keys.insert]
j={k="normal_mode"}


[keys.normal.space]
w = ":w"
q = ":q!"
e = "file_explorer_in_current_buffer_directory"
E = "file_explorer"
"[" = ":config-reload"
"]" = ":config-open"
t = { j = ":sh tmux split-window -v -l 30%% -c \"#{pane_current_path}\"", l = ":sh tmux split-window -h -c \"#{pane_current_path}\"" }
r = "format"

[keys.normal]
"space.z.z" = "center_view"
"space.z.l" = "scroll_right"
"space.z.h" = "scroll_left"
"space.z.k" = "scroll_up"
"space.z.j" = "scroll_down"
X = "delete_selection"
d = "extend_line_below"
D = "extend_to_line_bounds"
x = "delete_selection_noyank"
L = ["delete_selection", "paste_after"]
H = ["delete_selection", "move_char_left", "paste_before"]
J = ["extend_to_line_bounds", "delete_selection", "paste_after"]
K = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
backspace = "delete_char_backward"
# ret = ["insert_mode", "ret", "normal_mode"]
g.k = ":sh tmux next-window"
g.j = ":sh tmux previous-window"
g.n = ":sh tmux new-window"
s.n = ":sh tmux new-session"
s.k = ":sh tmux switch-client -n"
s.j = ":sh tmux switch-client -p"
z.v = ":sh tmux split-window -v"
z.h = ":sh tmux split-window -h"
z.j = ":sh tmux select-pane -D"
z.k = ":sh tmux select-pane -U"
z.H = ":sh tmux select-pane -L"  # Capital H for left
z.l = ":sh tmux select-pane -R"
z.z = ":sh tmux select-pane -t :.+"

[keys.select]
X = "delete_selection"
d = "extend_line_below"
D = "extend_to_line_bounds"
x = "delete_selection_noyank"
L = ["delete_selection", "paste_after"]
H = ["delete_selection","move_char_left", "paste_before"]
J = ["extend_to_line_bounds", "delete_selection", "paste_after"]
K = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
esc="normal_mode"

[editor]
auto-info = false
idle-timeout = 200        
cursorline = true
line-number = "relative"
completion-timeout = 100  
auto-format = false
bufferline = "never"

[editor.cursor-shape]
insert="bar"
normal="block"

[editor.lsp]
display-messages = true
display-inlay-hints = true
