theme = "dracula"

[keys.insert]
j={k="normal_mode"}


[keys.normal.space]
w = ":w"
q = ":q!"
e = "file_explorer_in_current_buffer_directory"
E = "file_explorer"
"[" = ":config-reload"
"]" = ":config-open"
t = { j = ":sh tmux split-window -v -l 30%% -c \"#{pane_current_path}\"", l = ":sh tmux split-window -h -c \"#{pane_current_path}\"" }

[keys.normal]
L = ["delete_selection", "paste_after"]
H = ["delete_selection", "move_char_left", "paste_before"]
J = ["extend_to_line_bounds", "delete_selection", "paste_after"]
K = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
ret = ["open_below", "normal_mode"]

[keys.select]
L = ["delete_selection", "paste_after"]
H = ["delete_selection","move_char_left", "paste_before"]
J = ["extend_to_line_bounds", "delete_selection", "paste_after"]
K = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
j={k="normal_mode"}

[editor]
idle-timeout = 200        
completion-timeout = 100  
auto-format = true
bufferline = "never"
